name: Manual trigger
on:
   workflow_dispatch:
   
jobs:
  Manual:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3    
      - name: Run HoneygainPot
        run: python main.py
        env:
          MAIL: ${{ secrets.MAIL }}
          PASS: ${{ secrets.PASS }}
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
          IsGit: 1
          IsJWT: 1 # <- 0 = Use Mail and Pass ; 1 = Use Token (Default is 1)
